# Abstract {.unnumbered}


Today the video game market offers thousands of products of many different genres, budgets, and prices. It is difficult for developers of games to get noticed on online platforms when they lack marketing budget due to the sheer size of these platforms, and the time it takes for users to determine if they want to purchase a game. The objective of this project is to provide a tool that can determine the success of a PC game based on data that is available before the game is released, such as categories and platforms. A dataset that is extracted from Steam and SteamSpy will be used to get information about games for training and testing. Data cleanup and dimensionality reduction techniques will be necessary in order to get good data to train the models with. Since we are only concerned with the current market, the database will be reduced to only include relevant titles that have been released in the last couple of years. Determining which model to use for the dataset can be a complex process as many different factors such as performance, complexity, explainability and the size of the dataset need to be taken into account. Machine learning models including Gaussian Naive Bayes, Lasso regression, KNN, and Decision Trees will be compared to determine which model best suits the dataset. the best suited model will generally be decided based upon the results of metrics like r2 score, f1-score, recall and precision as well how explainable the results are.
