# Conclusion

In conclusion,the decision tree regressor model was chosen as it yielded the best performance metrics on the dataset. When comparing accuracy, r2_scores, precision and f1_scores of various models, the decision tree model regressor consistently performed the best. It seems  the data set benefits from the various strengths of decision trees such as being able to handle non-linear relationships as well as handling both numerical and categorical data. This implies that the dataset contains non-linear relationships between variables and a mixture of both categorical and numerical data which provides a possible explanation for the poor performance of the other models aside from KNN. Future research on this topic should put more emphasis on obtaining accurate values for the number of owners since the current estimated value is an estimation between a broad range. An alternative solution could possibly be to replace the number of owners column with a sales column as it may be easier to track.